/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-01 18:14:47 UTC)
 * on 2014-04-04 at 03:39:42 UTC 
 * Modify at your own risk.
 */

package com.appspot.mac_books.bookSystem.model;

/**
 * Model definition for DatabaseMetaData.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the bookSystem. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DatabaseMetaData extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean catalogAtStart;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String catalogSeparator;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String catalogTerm;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ResultSet catalogs;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ResultSet clientInfoProperties;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Connection connection;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer databaseMajorVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer databaseMinorVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String databaseProductName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String databaseProductVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer defaultTransactionIsolation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer driverMajorVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer driverMinorVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String driverName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String driverVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String extraNameCharacters;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String identifierQuoteString;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer jdbcmajorVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer jdbcminorVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxBinaryLiteralLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxCatalogNameLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxCharLiteralLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxColumnNameLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxColumnsInGroupBy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxColumnsInIndex;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxColumnsInOrderBy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxColumnsInSelect;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxColumnsInTable;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxConnections;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxCursorNameLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxIndexLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxProcedureNameLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxRowSize;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxSchemaNameLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxStatementLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxStatements;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxTableNameLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxTablesInSelect;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxUserNameLength;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String numericFunctions;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String procedureTerm;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean readOnly;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer resultSetHoldability;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String rowIdLifetime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String schemaTerm;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ResultSet schemas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String searchStringEscape;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sqlkeywords;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer sqlstateType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String stringFunctions;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String systemFunctions;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ResultSet tableTypes;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String timeDateFunctions;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ResultSet typeInfo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String url;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCatalogAtStart() {
    return catalogAtStart;
  }

  /**
   * @param catalogAtStart catalogAtStart or {@code null} for none
   */
  public DatabaseMetaData setCatalogAtStart(java.lang.Boolean catalogAtStart) {
    this.catalogAtStart = catalogAtStart;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCatalogSeparator() {
    return catalogSeparator;
  }

  /**
   * @param catalogSeparator catalogSeparator or {@code null} for none
   */
  public DatabaseMetaData setCatalogSeparator(java.lang.String catalogSeparator) {
    this.catalogSeparator = catalogSeparator;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCatalogTerm() {
    return catalogTerm;
  }

  /**
   * @param catalogTerm catalogTerm or {@code null} for none
   */
  public DatabaseMetaData setCatalogTerm(java.lang.String catalogTerm) {
    this.catalogTerm = catalogTerm;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ResultSet getCatalogs() {
    return catalogs;
  }

  /**
   * @param catalogs catalogs or {@code null} for none
   */
  public DatabaseMetaData setCatalogs(ResultSet catalogs) {
    this.catalogs = catalogs;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ResultSet getClientInfoProperties() {
    return clientInfoProperties;
  }

  /**
   * @param clientInfoProperties clientInfoProperties or {@code null} for none
   */
  public DatabaseMetaData setClientInfoProperties(ResultSet clientInfoProperties) {
    this.clientInfoProperties = clientInfoProperties;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Connection getConnection() {
    return connection;
  }

  /**
   * @param connection connection or {@code null} for none
   */
  public DatabaseMetaData setConnection(Connection connection) {
    this.connection = connection;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDatabaseMajorVersion() {
    return databaseMajorVersion;
  }

  /**
   * @param databaseMajorVersion databaseMajorVersion or {@code null} for none
   */
  public DatabaseMetaData setDatabaseMajorVersion(java.lang.Integer databaseMajorVersion) {
    this.databaseMajorVersion = databaseMajorVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDatabaseMinorVersion() {
    return databaseMinorVersion;
  }

  /**
   * @param databaseMinorVersion databaseMinorVersion or {@code null} for none
   */
  public DatabaseMetaData setDatabaseMinorVersion(java.lang.Integer databaseMinorVersion) {
    this.databaseMinorVersion = databaseMinorVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDatabaseProductName() {
    return databaseProductName;
  }

  /**
   * @param databaseProductName databaseProductName or {@code null} for none
   */
  public DatabaseMetaData setDatabaseProductName(java.lang.String databaseProductName) {
    this.databaseProductName = databaseProductName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDatabaseProductVersion() {
    return databaseProductVersion;
  }

  /**
   * @param databaseProductVersion databaseProductVersion or {@code null} for none
   */
  public DatabaseMetaData setDatabaseProductVersion(java.lang.String databaseProductVersion) {
    this.databaseProductVersion = databaseProductVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDefaultTransactionIsolation() {
    return defaultTransactionIsolation;
  }

  /**
   * @param defaultTransactionIsolation defaultTransactionIsolation or {@code null} for none
   */
  public DatabaseMetaData setDefaultTransactionIsolation(java.lang.Integer defaultTransactionIsolation) {
    this.defaultTransactionIsolation = defaultTransactionIsolation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDriverMajorVersion() {
    return driverMajorVersion;
  }

  /**
   * @param driverMajorVersion driverMajorVersion or {@code null} for none
   */
  public DatabaseMetaData setDriverMajorVersion(java.lang.Integer driverMajorVersion) {
    this.driverMajorVersion = driverMajorVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDriverMinorVersion() {
    return driverMinorVersion;
  }

  /**
   * @param driverMinorVersion driverMinorVersion or {@code null} for none
   */
  public DatabaseMetaData setDriverMinorVersion(java.lang.Integer driverMinorVersion) {
    this.driverMinorVersion = driverMinorVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDriverName() {
    return driverName;
  }

  /**
   * @param driverName driverName or {@code null} for none
   */
  public DatabaseMetaData setDriverName(java.lang.String driverName) {
    this.driverName = driverName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDriverVersion() {
    return driverVersion;
  }

  /**
   * @param driverVersion driverVersion or {@code null} for none
   */
  public DatabaseMetaData setDriverVersion(java.lang.String driverVersion) {
    this.driverVersion = driverVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getExtraNameCharacters() {
    return extraNameCharacters;
  }

  /**
   * @param extraNameCharacters extraNameCharacters or {@code null} for none
   */
  public DatabaseMetaData setExtraNameCharacters(java.lang.String extraNameCharacters) {
    this.extraNameCharacters = extraNameCharacters;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdentifierQuoteString() {
    return identifierQuoteString;
  }

  /**
   * @param identifierQuoteString identifierQuoteString or {@code null} for none
   */
  public DatabaseMetaData setIdentifierQuoteString(java.lang.String identifierQuoteString) {
    this.identifierQuoteString = identifierQuoteString;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getJdbcmajorVersion() {
    return jdbcmajorVersion;
  }

  /**
   * @param jdbcmajorVersion jdbcmajorVersion or {@code null} for none
   */
  public DatabaseMetaData setJdbcmajorVersion(java.lang.Integer jdbcmajorVersion) {
    this.jdbcmajorVersion = jdbcmajorVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getJdbcminorVersion() {
    return jdbcminorVersion;
  }

  /**
   * @param jdbcminorVersion jdbcminorVersion or {@code null} for none
   */
  public DatabaseMetaData setJdbcminorVersion(java.lang.Integer jdbcminorVersion) {
    this.jdbcminorVersion = jdbcminorVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxBinaryLiteralLength() {
    return maxBinaryLiteralLength;
  }

  /**
   * @param maxBinaryLiteralLength maxBinaryLiteralLength or {@code null} for none
   */
  public DatabaseMetaData setMaxBinaryLiteralLength(java.lang.Integer maxBinaryLiteralLength) {
    this.maxBinaryLiteralLength = maxBinaryLiteralLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxCatalogNameLength() {
    return maxCatalogNameLength;
  }

  /**
   * @param maxCatalogNameLength maxCatalogNameLength or {@code null} for none
   */
  public DatabaseMetaData setMaxCatalogNameLength(java.lang.Integer maxCatalogNameLength) {
    this.maxCatalogNameLength = maxCatalogNameLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxCharLiteralLength() {
    return maxCharLiteralLength;
  }

  /**
   * @param maxCharLiteralLength maxCharLiteralLength or {@code null} for none
   */
  public DatabaseMetaData setMaxCharLiteralLength(java.lang.Integer maxCharLiteralLength) {
    this.maxCharLiteralLength = maxCharLiteralLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxColumnNameLength() {
    return maxColumnNameLength;
  }

  /**
   * @param maxColumnNameLength maxColumnNameLength or {@code null} for none
   */
  public DatabaseMetaData setMaxColumnNameLength(java.lang.Integer maxColumnNameLength) {
    this.maxColumnNameLength = maxColumnNameLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxColumnsInGroupBy() {
    return maxColumnsInGroupBy;
  }

  /**
   * @param maxColumnsInGroupBy maxColumnsInGroupBy or {@code null} for none
   */
  public DatabaseMetaData setMaxColumnsInGroupBy(java.lang.Integer maxColumnsInGroupBy) {
    this.maxColumnsInGroupBy = maxColumnsInGroupBy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxColumnsInIndex() {
    return maxColumnsInIndex;
  }

  /**
   * @param maxColumnsInIndex maxColumnsInIndex or {@code null} for none
   */
  public DatabaseMetaData setMaxColumnsInIndex(java.lang.Integer maxColumnsInIndex) {
    this.maxColumnsInIndex = maxColumnsInIndex;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxColumnsInOrderBy() {
    return maxColumnsInOrderBy;
  }

  /**
   * @param maxColumnsInOrderBy maxColumnsInOrderBy or {@code null} for none
   */
  public DatabaseMetaData setMaxColumnsInOrderBy(java.lang.Integer maxColumnsInOrderBy) {
    this.maxColumnsInOrderBy = maxColumnsInOrderBy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxColumnsInSelect() {
    return maxColumnsInSelect;
  }

  /**
   * @param maxColumnsInSelect maxColumnsInSelect or {@code null} for none
   */
  public DatabaseMetaData setMaxColumnsInSelect(java.lang.Integer maxColumnsInSelect) {
    this.maxColumnsInSelect = maxColumnsInSelect;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxColumnsInTable() {
    return maxColumnsInTable;
  }

  /**
   * @param maxColumnsInTable maxColumnsInTable or {@code null} for none
   */
  public DatabaseMetaData setMaxColumnsInTable(java.lang.Integer maxColumnsInTable) {
    this.maxColumnsInTable = maxColumnsInTable;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxConnections() {
    return maxConnections;
  }

  /**
   * @param maxConnections maxConnections or {@code null} for none
   */
  public DatabaseMetaData setMaxConnections(java.lang.Integer maxConnections) {
    this.maxConnections = maxConnections;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxCursorNameLength() {
    return maxCursorNameLength;
  }

  /**
   * @param maxCursorNameLength maxCursorNameLength or {@code null} for none
   */
  public DatabaseMetaData setMaxCursorNameLength(java.lang.Integer maxCursorNameLength) {
    this.maxCursorNameLength = maxCursorNameLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxIndexLength() {
    return maxIndexLength;
  }

  /**
   * @param maxIndexLength maxIndexLength or {@code null} for none
   */
  public DatabaseMetaData setMaxIndexLength(java.lang.Integer maxIndexLength) {
    this.maxIndexLength = maxIndexLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxProcedureNameLength() {
    return maxProcedureNameLength;
  }

  /**
   * @param maxProcedureNameLength maxProcedureNameLength or {@code null} for none
   */
  public DatabaseMetaData setMaxProcedureNameLength(java.lang.Integer maxProcedureNameLength) {
    this.maxProcedureNameLength = maxProcedureNameLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxRowSize() {
    return maxRowSize;
  }

  /**
   * @param maxRowSize maxRowSize or {@code null} for none
   */
  public DatabaseMetaData setMaxRowSize(java.lang.Integer maxRowSize) {
    this.maxRowSize = maxRowSize;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxSchemaNameLength() {
    return maxSchemaNameLength;
  }

  /**
   * @param maxSchemaNameLength maxSchemaNameLength or {@code null} for none
   */
  public DatabaseMetaData setMaxSchemaNameLength(java.lang.Integer maxSchemaNameLength) {
    this.maxSchemaNameLength = maxSchemaNameLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxStatementLength() {
    return maxStatementLength;
  }

  /**
   * @param maxStatementLength maxStatementLength or {@code null} for none
   */
  public DatabaseMetaData setMaxStatementLength(java.lang.Integer maxStatementLength) {
    this.maxStatementLength = maxStatementLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxStatements() {
    return maxStatements;
  }

  /**
   * @param maxStatements maxStatements or {@code null} for none
   */
  public DatabaseMetaData setMaxStatements(java.lang.Integer maxStatements) {
    this.maxStatements = maxStatements;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxTableNameLength() {
    return maxTableNameLength;
  }

  /**
   * @param maxTableNameLength maxTableNameLength or {@code null} for none
   */
  public DatabaseMetaData setMaxTableNameLength(java.lang.Integer maxTableNameLength) {
    this.maxTableNameLength = maxTableNameLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxTablesInSelect() {
    return maxTablesInSelect;
  }

  /**
   * @param maxTablesInSelect maxTablesInSelect or {@code null} for none
   */
  public DatabaseMetaData setMaxTablesInSelect(java.lang.Integer maxTablesInSelect) {
    this.maxTablesInSelect = maxTablesInSelect;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxUserNameLength() {
    return maxUserNameLength;
  }

  /**
   * @param maxUserNameLength maxUserNameLength or {@code null} for none
   */
  public DatabaseMetaData setMaxUserNameLength(java.lang.Integer maxUserNameLength) {
    this.maxUserNameLength = maxUserNameLength;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNumericFunctions() {
    return numericFunctions;
  }

  /**
   * @param numericFunctions numericFunctions or {@code null} for none
   */
  public DatabaseMetaData setNumericFunctions(java.lang.String numericFunctions) {
    this.numericFunctions = numericFunctions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProcedureTerm() {
    return procedureTerm;
  }

  /**
   * @param procedureTerm procedureTerm or {@code null} for none
   */
  public DatabaseMetaData setProcedureTerm(java.lang.String procedureTerm) {
    this.procedureTerm = procedureTerm;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getReadOnly() {
    return readOnly;
  }

  /**
   * @param readOnly readOnly or {@code null} for none
   */
  public DatabaseMetaData setReadOnly(java.lang.Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResultSetHoldability() {
    return resultSetHoldability;
  }

  /**
   * @param resultSetHoldability resultSetHoldability or {@code null} for none
   */
  public DatabaseMetaData setResultSetHoldability(java.lang.Integer resultSetHoldability) {
    this.resultSetHoldability = resultSetHoldability;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRowIdLifetime() {
    return rowIdLifetime;
  }

  /**
   * @param rowIdLifetime rowIdLifetime or {@code null} for none
   */
  public DatabaseMetaData setRowIdLifetime(java.lang.String rowIdLifetime) {
    this.rowIdLifetime = rowIdLifetime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSchemaTerm() {
    return schemaTerm;
  }

  /**
   * @param schemaTerm schemaTerm or {@code null} for none
   */
  public DatabaseMetaData setSchemaTerm(java.lang.String schemaTerm) {
    this.schemaTerm = schemaTerm;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ResultSet getSchemas() {
    return schemas;
  }

  /**
   * @param schemas schemas or {@code null} for none
   */
  public DatabaseMetaData setSchemas(ResultSet schemas) {
    this.schemas = schemas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSearchStringEscape() {
    return searchStringEscape;
  }

  /**
   * @param searchStringEscape searchStringEscape or {@code null} for none
   */
  public DatabaseMetaData setSearchStringEscape(java.lang.String searchStringEscape) {
    this.searchStringEscape = searchStringEscape;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSqlkeywords() {
    return sqlkeywords;
  }

  /**
   * @param sqlkeywords sqlkeywords or {@code null} for none
   */
  public DatabaseMetaData setSqlkeywords(java.lang.String sqlkeywords) {
    this.sqlkeywords = sqlkeywords;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSqlstateType() {
    return sqlstateType;
  }

  /**
   * @param sqlstateType sqlstateType or {@code null} for none
   */
  public DatabaseMetaData setSqlstateType(java.lang.Integer sqlstateType) {
    this.sqlstateType = sqlstateType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStringFunctions() {
    return stringFunctions;
  }

  /**
   * @param stringFunctions stringFunctions or {@code null} for none
   */
  public DatabaseMetaData setStringFunctions(java.lang.String stringFunctions) {
    this.stringFunctions = stringFunctions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSystemFunctions() {
    return systemFunctions;
  }

  /**
   * @param systemFunctions systemFunctions or {@code null} for none
   */
  public DatabaseMetaData setSystemFunctions(java.lang.String systemFunctions) {
    this.systemFunctions = systemFunctions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ResultSet getTableTypes() {
    return tableTypes;
  }

  /**
   * @param tableTypes tableTypes or {@code null} for none
   */
  public DatabaseMetaData setTableTypes(ResultSet tableTypes) {
    this.tableTypes = tableTypes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTimeDateFunctions() {
    return timeDateFunctions;
  }

  /**
   * @param timeDateFunctions timeDateFunctions or {@code null} for none
   */
  public DatabaseMetaData setTimeDateFunctions(java.lang.String timeDateFunctions) {
    this.timeDateFunctions = timeDateFunctions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ResultSet getTypeInfo() {
    return typeInfo;
  }

  /**
   * @param typeInfo typeInfo or {@code null} for none
   */
  public DatabaseMetaData setTypeInfo(ResultSet typeInfo) {
    this.typeInfo = typeInfo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUrl() {
    return url;
  }

  /**
   * @param url url or {@code null} for none
   */
  public DatabaseMetaData setUrl(java.lang.String url) {
    this.url = url;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserName() {
    return userName;
  }

  /**
   * @param userName userName or {@code null} for none
   */
  public DatabaseMetaData setUserName(java.lang.String userName) {
    this.userName = userName;
    return this;
  }

  @Override
  public DatabaseMetaData set(String fieldName, Object value) {
    return (DatabaseMetaData) super.set(fieldName, value);
  }

  @Override
  public DatabaseMetaData clone() {
    return (DatabaseMetaData) super.clone();
  }

}
