/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-04-29 at 05:50:09 UTC 
 * Modify at your own risk.
 */

package com.appspot.mac_books.bookSystem.model;

/**
 * Model definition for ResultSet.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the bookSystem. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ResultSet extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean afterLast;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean beforeFirst;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean closed;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer concurrency;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cursorName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer fetchDirection;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer fetchSize;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean first;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer holdability;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean last;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ResultSetMetaData metaData;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer row;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Statement statement;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer type;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private SQLWarning warnings;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAfterLast() {
    return afterLast;
  }

  /**
   * @param afterLast afterLast or {@code null} for none
   */
  public ResultSet setAfterLast(java.lang.Boolean afterLast) {
    this.afterLast = afterLast;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getBeforeFirst() {
    return beforeFirst;
  }

  /**
   * @param beforeFirst beforeFirst or {@code null} for none
   */
  public ResultSet setBeforeFirst(java.lang.Boolean beforeFirst) {
    this.beforeFirst = beforeFirst;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getClosed() {
    return closed;
  }

  /**
   * @param closed closed or {@code null} for none
   */
  public ResultSet setClosed(java.lang.Boolean closed) {
    this.closed = closed;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getConcurrency() {
    return concurrency;
  }

  /**
   * @param concurrency concurrency or {@code null} for none
   */
  public ResultSet setConcurrency(java.lang.Integer concurrency) {
    this.concurrency = concurrency;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCursorName() {
    return cursorName;
  }

  /**
   * @param cursorName cursorName or {@code null} for none
   */
  public ResultSet setCursorName(java.lang.String cursorName) {
    this.cursorName = cursorName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFetchDirection() {
    return fetchDirection;
  }

  /**
   * @param fetchDirection fetchDirection or {@code null} for none
   */
  public ResultSet setFetchDirection(java.lang.Integer fetchDirection) {
    this.fetchDirection = fetchDirection;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFetchSize() {
    return fetchSize;
  }

  /**
   * @param fetchSize fetchSize or {@code null} for none
   */
  public ResultSet setFetchSize(java.lang.Integer fetchSize) {
    this.fetchSize = fetchSize;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getFirst() {
    return first;
  }

  /**
   * @param first first or {@code null} for none
   */
  public ResultSet setFirst(java.lang.Boolean first) {
    this.first = first;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getHoldability() {
    return holdability;
  }

  /**
   * @param holdability holdability or {@code null} for none
   */
  public ResultSet setHoldability(java.lang.Integer holdability) {
    this.holdability = holdability;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getLast() {
    return last;
  }

  /**
   * @param last last or {@code null} for none
   */
  public ResultSet setLast(java.lang.Boolean last) {
    this.last = last;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ResultSetMetaData getMetaData() {
    return metaData;
  }

  /**
   * @param metaData metaData or {@code null} for none
   */
  public ResultSet setMetaData(ResultSetMetaData metaData) {
    this.metaData = metaData;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getRow() {
    return row;
  }

  /**
   * @param row row or {@code null} for none
   */
  public ResultSet setRow(java.lang.Integer row) {
    this.row = row;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Statement getStatement() {
    return statement;
  }

  /**
   * @param statement statement or {@code null} for none
   */
  public ResultSet setStatement(Statement statement) {
    this.statement = statement;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public ResultSet setType(java.lang.Integer type) {
    this.type = type;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public SQLWarning getWarnings() {
    return warnings;
  }

  /**
   * @param warnings warnings or {@code null} for none
   */
  public ResultSet setWarnings(SQLWarning warnings) {
    this.warnings = warnings;
    return this;
  }

  @Override
  public ResultSet set(String fieldName, Object value) {
    return (ResultSet) super.set(fieldName, value);
  }

  @Override
  public ResultSet clone() {
    return (ResultSet) super.clone();
  }

}
