/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-01 18:14:47 UTC)
 * on 2014-04-04 at 03:39:42 UTC 
 * Modify at your own risk.
 */

package com.appspot.mac_books.bookSystem.model;

/**
 * Model definition for Statement.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the bookSystem. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Statement extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean closeOnCompletion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean closed;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Connection connection;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cursorName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean escapeProcessing;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer fetchDirection;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer fetchSize;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ResultSet generatedKeys;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxFieldSize;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxRows;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean moreResults;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean poolable;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer queryTimeout;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ResultSet resultSet;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer resultSetConcurrency;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer resultSetHoldability;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer resultSetType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer updateCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private SQLWarning warnings;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCloseOnCompletion() {
    return closeOnCompletion;
  }

  /**
   * @param closeOnCompletion closeOnCompletion or {@code null} for none
   */
  public Statement setCloseOnCompletion(java.lang.Boolean closeOnCompletion) {
    this.closeOnCompletion = closeOnCompletion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getClosed() {
    return closed;
  }

  /**
   * @param closed closed or {@code null} for none
   */
  public Statement setClosed(java.lang.Boolean closed) {
    this.closed = closed;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Connection getConnection() {
    return connection;
  }

  /**
   * @param connection connection or {@code null} for none
   */
  public Statement setConnection(Connection connection) {
    this.connection = connection;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCursorName() {
    return cursorName;
  }

  /**
   * @param cursorName cursorName or {@code null} for none
   */
  public Statement setCursorName(java.lang.String cursorName) {
    this.cursorName = cursorName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getEscapeProcessing() {
    return escapeProcessing;
  }

  /**
   * @param escapeProcessing escapeProcessing or {@code null} for none
   */
  public Statement setEscapeProcessing(java.lang.Boolean escapeProcessing) {
    this.escapeProcessing = escapeProcessing;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFetchDirection() {
    return fetchDirection;
  }

  /**
   * @param fetchDirection fetchDirection or {@code null} for none
   */
  public Statement setFetchDirection(java.lang.Integer fetchDirection) {
    this.fetchDirection = fetchDirection;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFetchSize() {
    return fetchSize;
  }

  /**
   * @param fetchSize fetchSize or {@code null} for none
   */
  public Statement setFetchSize(java.lang.Integer fetchSize) {
    this.fetchSize = fetchSize;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ResultSet getGeneratedKeys() {
    return generatedKeys;
  }

  /**
   * @param generatedKeys generatedKeys or {@code null} for none
   */
  public Statement setGeneratedKeys(ResultSet generatedKeys) {
    this.generatedKeys = generatedKeys;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxFieldSize() {
    return maxFieldSize;
  }

  /**
   * @param maxFieldSize maxFieldSize or {@code null} for none
   */
  public Statement setMaxFieldSize(java.lang.Integer maxFieldSize) {
    this.maxFieldSize = maxFieldSize;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxRows() {
    return maxRows;
  }

  /**
   * @param maxRows maxRows or {@code null} for none
   */
  public Statement setMaxRows(java.lang.Integer maxRows) {
    this.maxRows = maxRows;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getMoreResults() {
    return moreResults;
  }

  /**
   * @param moreResults moreResults or {@code null} for none
   */
  public Statement setMoreResults(java.lang.Boolean moreResults) {
    this.moreResults = moreResults;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getPoolable() {
    return poolable;
  }

  /**
   * @param poolable poolable or {@code null} for none
   */
  public Statement setPoolable(java.lang.Boolean poolable) {
    this.poolable = poolable;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getQueryTimeout() {
    return queryTimeout;
  }

  /**
   * @param queryTimeout queryTimeout or {@code null} for none
   */
  public Statement setQueryTimeout(java.lang.Integer queryTimeout) {
    this.queryTimeout = queryTimeout;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ResultSet getResultSet() {
    return resultSet;
  }

  /**
   * @param resultSet resultSet or {@code null} for none
   */
  public Statement setResultSet(ResultSet resultSet) {
    this.resultSet = resultSet;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResultSetConcurrency() {
    return resultSetConcurrency;
  }

  /**
   * @param resultSetConcurrency resultSetConcurrency or {@code null} for none
   */
  public Statement setResultSetConcurrency(java.lang.Integer resultSetConcurrency) {
    this.resultSetConcurrency = resultSetConcurrency;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResultSetHoldability() {
    return resultSetHoldability;
  }

  /**
   * @param resultSetHoldability resultSetHoldability or {@code null} for none
   */
  public Statement setResultSetHoldability(java.lang.Integer resultSetHoldability) {
    this.resultSetHoldability = resultSetHoldability;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResultSetType() {
    return resultSetType;
  }

  /**
   * @param resultSetType resultSetType or {@code null} for none
   */
  public Statement setResultSetType(java.lang.Integer resultSetType) {
    this.resultSetType = resultSetType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getUpdateCount() {
    return updateCount;
  }

  /**
   * @param updateCount updateCount or {@code null} for none
   */
  public Statement setUpdateCount(java.lang.Integer updateCount) {
    this.updateCount = updateCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public SQLWarning getWarnings() {
    return warnings;
  }

  /**
   * @param warnings warnings or {@code null} for none
   */
  public Statement setWarnings(SQLWarning warnings) {
    this.warnings = warnings;
    return this;
  }

  @Override
  public Statement set(String fieldName, Object value) {
    return (Statement) super.set(fieldName, value);
  }

  @Override
  public Statement clone() {
    return (Statement) super.clone();
  }

}
